#%RAML 1.0 NamedExample
values:
-  {
    "id": "1",
    "employee_name": "pankaj",
    "employee_salary": "1000",
    "employee_age": "25",
    "profile_image": ""
   }
-  {
   "id": "2",
   "employee_name": "Rahul",
   "employee_salary": "2000",
   "employee_age": "26",
   "profile_image": ""
   }